### PR TITLE
Ian

### PR DESCRIPTION
**Pull request by IanSmoothStack**
Fixed the problems I had with Avery and my files conflicting. Borrowers as a whole should be functional now. Will still need to update it and make it look better.

### CODE REVIEW

**Review by danielbarone — CHANGES_REQUESTED** [review]
You're pushing a few things that should be **gitignored**: 
- all .env files
- the stripe-service directory should be deleted
- the two application.properties files

You may have to:
- git rm -rf --cached .
- git add .

to get your gitignore to work properly

**Comment by IanSmoothStack** [comment]
Did what Dan suggested and pushed to my branch again

**Comment by IanSmoothStack** [comment]
got rid of stripe-service

**Review by AveryJ13 — CHANGES_REQUESTED** [review]
1. Show loans shows loans for all users not selected user
2. Error loading spinner never goes away.
3. Look into the table a bit more, worked for me but lagged out daniel. Idk whats going on there.
4. Sometimes the connections get refused sometimes they dont. I would double check CORS in your services
	to make sure its working correctly.
5. Never got past checkout book, just shows a spinner. 

Ensure functionality is working appropriately.

**Review by AveryJ13 — APPROVED** [review]
Works on my end, and the team thinks its good to approve. Good job Ian

**Review by danielbarone — APPROVED** [review]

**Pull request merged**
